### ISSUE TITLE
Starting and stopping a stream based on values from another stream

### ISSUE THREAD

**Issue by sammosampson** [paldepind/flyd#109]
For example I want to start an 'every' pulse stream when another stream changes value and pause it when the other stream changes to another value. Any ideas on the best way to do this?

**Comment by c-dante** [comment]
Streams in `flyd` are always active (to use `kefir` terms) -- that is, they're more like a property than a stream.

There is no way to "enable" or "disable" a stream, but you do have a ton of control through the `combine` api.

From what I gleam off your request, you can do something like:

```js
const debug = (name, s) => flyd.on((x) => console.log(name, x), s);
const a = flyd.stream(); // Start undefined
const b = flyd.stream(0); // Start at 0

const c = flyd.combine((a, b, self, changed) => {
  if (b() % 2 === 0) {
    c(a())
  }
}, [a, b]);

debug('a', a);
debug('b', b);
debug('c', c);
a(0);
b(1);
a(10)(15);
b(2);
a(1)(2)(3);

/* Expected:
b 0
a 0
c 0
b 1
a 10 // Notice that c skips 10 because b was odd during this call
a 15
b 2
c 15
a 1
c 1
a 2
c 2
a 3
c 3
*/
```

Again, not 100% on your use case or what you directly mean, but I'm demonstrating a way to use `flyd.combine` for some interesting logic. In this example, if `b` is even than `c` takes on `a`'s value, otherwise `c` is "frozen".

You could also keep c's state outside in a closure, if that's easier to work with.

**Comment by sammosampson** [comment]
Excellent this is exactly what I need thank you for this.

Chris

**Comment by StreetStrider** [comment]
flyd-keepwhen
flyd-cacheUntil

**Comment by c-dante** [comment]
If this is resolved, can you close this issue @sammosampson or @paldepind?
