### ISSUE TITLE
The name "flyd" is uncomfortable in the UK

### ISSUE THREAD

**Issue by stilvoid** [paldepind/flyd#12]
http://www.urbandictionary.com/define.php?term=flid

**Comment by paldepind** [comment]
How bad do you think this is? Flyd and flid are, after all, two different words.

Flyd is a danish word meaning float, afloat or flow. Do you think adding a mention of that to the readme would improve the situation?

**Comment by stilvoid** [comment]
I suppose it depends on your target audience. We were discussing JS frameworks and Flyd came up. The reactions varied from amusement to incredulity ;)

In reality, the name isn't really going to offend anyone but people will definitely snigger if someone tries to give a talk on Flyd.

If you're fixed on the name, an explanation of the derivation would definitely help.

**Comment by paldepind** [comment]
Ah, I guess that if native english speaker pronounces "flyd" it could sound a lot like "flid". I, as a dane, certainly pronounce it in a way that doesn't sound like "flid" (so I will give the talks ;)).

The problem is that I really like the name and that I have 12 packages in npm using it.

It helps that people find it funny and not offensive. If the name was totally inappropriate to say it would be very bad.

**Comment by MJefferson** [comment]
There's also an urban dictionary for this spelling of "flid" as well: http://www.urbandictionary.com/define.php?term=flyd

Is there an origin story for the name "Flyd" other than it sounded cool in a discussion?

**Comment by paldepind** [comment]
@MJefferson Thanks for sharing. See my previous explanation:

> Flyd is a danish word meaning float, afloat or flow. Do you think adding a mention of that to the readme would improve the situation?

**Comment by paldepind** [comment]
[I've now added an explanation for the name in the readme.](https://github.com/paldepind/flyd#the-name)
