### ISSUE TITLE
Inconsistency with stream manipulation inside a stream

### ISSUE THREAD

**Issue by niant** [paldepind/flyd#177]
There seems to be inconsistency between flyd.map operations inside a stream body or I'm not using it correctly. Could you verify this?

```javascript
// helper function
const log = message => val => {
  console.log(message, val);
  return val;
};

const stream$ = flyd.stream(true);

flyd.stream(1).map(() => {
  stream$
    .map(log('this prints and returns true...'))
    .map(log('...but it never reaches here'));
});
```

It works correctly if `stream$` is created inline inside the flyd.map(), but if it's created outside: it'll only reach the first map, but not the second one.

Edit: flyd version is 0.2.6

**Comment by StreetStrider** [comment]
#160

**Comment by niant** [comment]
Thanks for a quick response!

#160 Would seem to be heavily related issue, though this is a bit different case with external stream handling inside another stream body. This happens on the newest flyd version 0.2.6. Do you happen to have any ideas on this?

**Comment by StreetStrider** [comment]
casting related people @paldepind @m59peacemaker

**Comment by nordfjord** [comment]
The problem area is here:
https://github.com/paldepind/flyd/blob/master/lib/index.js#L596-L603

when you first map over the stream the initial dependencies are met but you're inside a stream body so an update is pushed to the toUpdate array.
When the second map is performed its initial dependencies are not met so it's not pushed to the update array.

@paldepind I think the solution might be to push to the toUpdate array in both cases, I'll verify whether that works later.

**Comment by nordfjord** [comment]
Sorry, a bit more debugging leads me to this line: https://github.com/paldepind/flyd/blob/master/lib/index.js#L685

**Comment by niant** [comment]
Thank you for your input! I'm not that familiar with flyd inner workings yet, but that would seem like a logical explanation. 

I have tried to figure out logic in `inStream` and `deps`, since if I use `updateDeps(s)` above `markListeners(s, s.listeners);` this issue will work - but then again other tests fail (of course?).

**Comment by nordfjord** [comment]
inStream is used to track which stream is updating its dependencies at any time, this is a must for atomic updates, and to prevent infinite loops.

By calling `updateDeps` there you're breaking atomic updates leading to a bunch of tests failing

**Comment by m59peacemaker** [comment]
I don't know how to help with flyd. I made my own flyd-like thing that seems to do well with these nested behaviors without sacrificing atomic updates. My library is the same thing fundamentally but with my opinions on the api and the codebase is not at all similar. Unfortunately, I lack time to document it right now and I haven't used it much yet. Anyway, in case it helps, here's a passing test for this in my lib: https://github.com/m59peacemaker/js-wark/blob/master/lib/test/misc.test.js#L6

**Comment by shpuld** [comment]
We have been doing some further investigation on this issue with @niant and there are some findings.

First, there is a way to solve the specific problem in this issue without breaking any of the other tests, but it's ugly and I'm not convinced that it doesn't break something else that just isn't tested. Something like this:
```
var queueNext = false;
function updateStream(s) {
  if ((s.depsMet !== true && initialDepsNotMet(s)) ||
    (s.end !== undefined && s.end.val === true)) {
    if (queueNext) {
      toUpdate.push(function() {
        updateStream(s);
      });
    }
    return;
  }
  if (inStream !== undefined) {
    toUpdate.push(function() {
      updateStream(s);
    });
    queueNext = true;
    return;
  }
  queueNext = false;
  inStream = s;
  if (s.depsChanged) s.fnArgs[s.fnArgs.length - 1] = s.depsChanged;
  var returnVal = s.fn.apply(s.fn, s.fnArgs);
  if (returnVal !== undefined) {
    s(returnVal);
  }
  inStream = undefined;
  if (s.depsChanged !== undefined) s.depsChanged = [];
  s.shouldUpdate = false;
  if (flushing === false) flushUpdate();
}
```

Basically it just sets the state so that next stream updates know that their parents have been put in the toUpdate queue, which is why they don't have values, and that's why these should also be put into the queue instead of skipped. Perhaps there's a way to do the same thing without globals by actually going through the toUpdate queue or having a per-stream flag or something.

While testing this solution we found out that in these sort of nested stream updates atomic updates can already be broken with a test case like this:
```
var result = 0;
stream(1).map(function() {
  stream(0)
    .map(function(val) {
      result += 1;
      return val + 1;
    })
    .map(function(val) {
      result += 1;
      return val + 1;
    });
});
assert.equal(result, 2);
```

In this case without the hacky fix above, result will be 3 (it executes first map, second map, then first map again without the second), and with the fix it is 4 (first map, second map, then both again). Didn't quite figure out why this happens yet, but will continue investigating. This should probably be separated into its own issue but it's also related to this one.

Other thoughts after some investigation:
- maybe `inStream` could be a stack of sorts so it could handle nesting better, but I'm not sure how it would work in practice.
- the logic between immediate updates and deferred (toUpdate queue) updates seem to be very different and unintuitive and almost seems like it's asking for more bugs to be found, could there be a way of making things work in a more similar fashion in both cases?
- there's some very misleading naming in the code, `updateDeps` and `findDeps` both handle listeners and not deps, is it supposed to be like this?

**Comment by m59peacemaker** [comment]
flyd-style atomic updating is the hardest problem I have ever tried to tackle. I am not sure I got it right, but I did quite a lot of thinking about it and what I came up with, while surely far from ideal, seems to work and the code is at least somewhat manageable. Whatever happens with this issue for flyd, my hope is that it is solved by abstracting the atomic updating into its own module so that it can be independently tested and pick up all the other benefits of single-responsibility abstractions.

[Here's my module for atomic signaling](https://github.com/m59peacemaker/js-wark/blob/master/lib/util/signal-descendants-atomically.js#L7-L22), and [this is how my streams use it](https://github.com/m59peacemaker/js-wark/blob/master/lib/StreamBase.js#L8-L31).

I'm not saying my work is any good or helpful, but I share this just to say that I think it's really good to solve it with an independent module and before attempting to write that code, to flesh out exactly what an atomic update is. IIRC, when I finally made some progress, it started from drawing out things like [this](https://github.com/m59peacemaker/js-wark/blob/master/lib/util/signal-descendants-atomically.test.js#L150-L157) and then writing descriptions of what I was encountering in the diagrams. It is surely daunting trying to fix bugs in the flyd code with the various concerns all mixed together and not thoroughly defined.

**Comment by shpuld** [comment]
I looked at wark's code earlier, and it seems like it's written in a way that's way cleaner, but not necessarily useful when trying to patch up existing flyd code (as messy as it is), and performance could be another concern I think.

**Comment by m59peacemaker** [comment]
@shpuld True - performance can be a cost with some abstractions. I'm not sure how significant that would be in real-life usage. Hopefully someone can figure out a fix for flyd one way or another. Just seems so tough to build a mental model and have reasonable confidence in all the possible behaviors.

**Comment by m59peacemaker** [comment]
If anyone goes to work on an atomic signaling module or an adaptation of mine, I'd love to collaborate on it.

**Comment by paldepind** [comment]
Props to @shpuld for fixing this issue 🎉. The atomic update code in Flyd is indeed a bit tricky. Unfortunately, I 've had a lot of my plate in the last couple of months with my bachelor's thesis and finals. But, I'm very happy to see the conversation in this thread and that the issue was solved. Thank's a lot everyone!
