### ISSUE TITLE
Naming conventions

### ISSUE THREAD

**Issue by gyzerok** [paldepind/flyd#18]
Hi there!
I really like your approach to FRP. But why the hell dont you use standard  method names? ```afterSilence``` is ```debounce``` for sure I suppose.

**Comment by paldepind** [comment]
I'm glad you like the approach.

Why the hell I don't use standard names? Well, I actually do. I mostly use names from Elm because I believe Elm generally has the best names.

flyd-filter – Standard.
flyd-lift – Standard. Lift is well know in functional programming.
flyd-flatmap – Standard. Elm, Bacon and Kefir uses this name.
flyd-keepwhen – Standard. Elm uses this name.
flyd-obj – I'm not aware of other FRP libraries having something like this.
flyd-sampleon – Standard. Elm uses this name.
flyd-scanmerge – I'm not aware of other FRP libraries having something like this.
flyd-takeuntil – Standard. Elm and Bacon uses this name.
flyd-every - Standard. Elm uses this name.
flyd-aftersilence – I'm not aware of other FRP libraries having something exactly like this.
flyd-inlast – I'm not aware of other FRP libraries having something exactly like this.

The difference between `decounce` and `afterSilence` is that after silence does buffering. `debounce` only emits the values before the silence. You can implement it like this in Rx:

```javascript
function afterSilence(duration, obs) {
    return obs.buffer(function() { return obs.throttle(duration);
});
```

**Comment by gyzerok** [comment]
@paldepind ok, thanks its now more clear for me.
But the rea;ity is we are is Javascript not in Elm world. I guess Rx is more popular than Elm language itself :)

**Comment by paldepind** [comment]
@gyzerok most of these names have roots in functional programming.  And Flyd strives a be a FRP library that's more functional so reflecting that in the names makes sense to me.

I've considered adding a kind of "also known as" to the modules in the readme.
