### ISSUE TITLE
Example secret combination bug

### ISSUE THREAD

**Issue by cscalfani** [paldepind/flyd#21]
After getting the combination correct, clicksInLast5s still fires 6 more times each time causing the lift's function to display "You're not fast enough, try again!".

**Comment by paldepind** [comment]
Well spotted! I somehow missed that. Thanks for letting me know :+1: 

Unless you can spot a mistake in my fix I'll close this issue.

**Comment by cscalfani** [comment]
Thanks for the fix. I'm pretty new to your library so I wouldn't trust my assessment of the fix. But looking over the change, I don't see any issues assuming I understand how sampleon works, which I'm assuming is triggered by the click stream in this case.

**Comment by paldepind** [comment]
Great! Yes, it is ended triggered by the click stream. The triggering stream is the first argument since that makes 'sampleOn` most useful for partial application. It is more common to have a stream used as samplers for several other streams than having a stream you want sampled by a bunch of different streams. You can do both of course. It's only about making the common case the most convenient.

Thanks again for catching this mistake :)
